[build]
  base = "frontend/"
  publish = "." # CORRIGIDO AQUI! Agora é apenas um ponto.
  command = "" # Deixe vazio, pois é um site estático sem build complexo

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200